AFTER_STORY_CREATE = "Stories has created successfully."
NO_DATA_FOUND = "Stories not found."
SERVER_ERROR = "Server error has occurred."
STORY_EXISTS = "Story with %s already exists."
NO_RECORD = "Story not found."
SUCCESS_DELETE = "Story with id: `%s` was successfully deleted."
