"""init

Revision ID: abf2ca28c26f
Revises: 
Create Date: 2024-01-20 19:59:49.396204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abf2ca28c26f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
