"""add contacts table

Revision ID: 5ef9cfec12a5
Revises: 91864eff29ab
Create Date: 2024-01-22 01:45:52.795266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ef9cfec12a5"
down_revision: Union[str, None] = "91864eff29ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("post_address", sa.String(length=200), nullable=True),
        sa.Column("facebook", sa.String(length=500), nullable=True),
        sa.Column("instagram", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "user",
        "phone",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "phone",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_table("contacts")
    # ### end Alembic commands ###
