"""initial_cats

Revision ID: 7e74cb57e0c9
Revises: 22ebce52b91d
Create Date: 2024-01-23 16:25:37.898898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7e74cb57e0c9"
down_revision: Union[str, None] = "35404a437220"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("is_male", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cat_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cat_id", sa.Integer(), nullable=True),
        sa.Column("media_path", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["cat_id"],
            ["cats.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cat_photos")
    op.drop_table("cats")
    # ### end Alembic commands ###
