"""initial hero

Revision ID: 178c4abbeed3
Revises: 5356a24cac6d
Create Date: 2024-01-21 14:00:54.358020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "178c4abbeed3"
down_revision: Union[str, None] = "5356a24cac6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hero",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("sub_title", sa.String(length=200), nullable=False),
        sa.Column("media_path", sa.String(length=500), nullable=False),
        sa.Column("left_text", sa.String(length=200), nullable=False),
        sa.Column("right_text", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hero")
    # ### end Alembic commands ###
