"""initial_story

Revision ID: 22ebce52b91d
Revises: 5ef9cfec12a5
Create Date: 2024-01-22 11:46:07.416628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22ebce52b91d"
down_revision: Union[str, None] = "5ef9cfec12a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("text", sa.String(length=2000), nullable=True),
        sa.Column("media_path", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Stories")
    # ### end Alembic commands ###
