"""update contacts

Revision ID: c993f3ad1bc0
Revises: a85f6317dad6
Create Date: 2024-01-31 20:38:48.466047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c993f3ad1bc0'
down_revision: Union[str, None] = 'a85f6317dad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=35),
               existing_nullable=False)
    op.alter_column('contacts', 'post_address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'post_address',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
