"""add accountability table

Revision ID: 91864eff29ab
Revises: a1e72694a468
Create Date: 2024-01-22 01:13:47.951596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "91864eff29ab"
down_revision: Union[str, None] = "a1e72694a468"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accountability",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_path", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.drop_column("hero", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column(
    #     "hero",
    #     sa.Column(
    #         "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
    #     ),
    # )
    op.drop_table("accountability")
    # ### end Alembic commands ###
